//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta.Bases_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaVentasPorDiaDeSemana
    {
        public int IdVenta { get; set; }
        public Nullable<decimal> Domingo { get; set; }
        public Nullable<decimal> Lunes { get; set; }
        public Nullable<decimal> Martes { get; set; }
        public Nullable<decimal> Miércoles { get; set; }
        public Nullable<decimal> Jueves { get; set; }
        public Nullable<decimal> Viernes { get; set; }
        public Nullable<decimal> Sábado { get; set; }
    }
}
